<?php

/**
 * @file
 * Support for configurable user profiles.
 */

use Drupal\profile2\Plugin\Core\Entity\Profile;
use Drupal\profile2\Plugin\Core\Entity\ProfileType;
use Drupal\user\Plugin\Core\Entity\User;

/**
 * Implements hook_entity_info().
 */
function profile2_entity_info(&$info) {
  $config_names = config_get_storage_names_with_prefix('profile2.type.');
  foreach ($config_names as $config_name) {
    $config = config($config_name);
    $info['profile2']['bundles'][$config->get('id')] = array(
      'label' => $config->get('label'),
      'admin' => array(
        'path' => 'admin/people/profiles/manage/%profile2_type',
        'real path' => 'admin/people/profiles/manage/' . $config->get('id'),
        'bundle argument' => 4,
        'access arguments' => array('administer profile types'),
      ),
    );
  }
}

/**
 * Entity URI callback for profiles.
 *
 * @param Drupal\profile2\Plugin\Core\Entity\Profile $profile
 *   A profile entity.
 */
function profile2_profile_uri(Profile $profile) {
  $uri = entity_load('user', $profile->uid)->uri();
  $uri['options']['fragment'] = 'profile-' . $profile->bundle();
  return $uri;
}

/**
 * Entity URI callback for profile types.
 *
 * @param Drupal\profile2\Plugin\Core\Entity\ProfileType $profile_type
 *   A profile type entity.
 */
function profile2_profile_type_uri(ProfileType $profile_type) {
  return array(
    'path' => 'admin/people/profiles/manage/' . $profile_type->id(),
  );
}

/**
 * Implements hook_menu().
 */
function profile2_menu() {
  $items['admin/people/profiles'] = array(
    'title' => 'Profile types',
    'description' => 'Manage profile types, including fields.',
    'page callback' => 'profile2_type_list_page',
    'access arguments' => array('administer profile types'),
    'type' => MENU_LOCAL_TASK,
    // @todo User module: Apply custom/higher weights to Permissions and Roles.
    'weight' => -1,
    'file' => 'profile2.admin.inc',
  );
  $items['admin/people/profiles/add'] = array(
    'title' => 'Add profile type',
    'page callback' => 'profile2_type_add',
    'access arguments' => array('administer profile types'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'profile2.admin.inc',
  );
  $items['admin/people/profiles/manage/%profile2_type'] = array(
    'title' => 'Edit profile type',
    'page callback' => 'profile2_type_edit',
    'page arguments' => array(4),
    'access arguments' => array('administer profile types'),
    'file' => 'profile2.admin.inc',
  );
  $items['admin/people/profiles/manage/%profile2_type/edit'] = array(
    'title' => 'Edit',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['admin/people/profiles/manage/%profile2_type/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('profile2_type_delete_form', 4),
    'access arguments' => array('administer profile types'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'profile2.admin.inc',
  );

  // @todo Move into User module.
  $items['user/%user/edit/account'] = array(
    'title' => 'Account',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['user/%user/edit/%profile2_menu'] = array(
    // @see http://drupal.org/node/1863502
    'load arguments' => array(1, 'edit'),
    'load arguments' => array('%map', 'edit'),
    'title' => 'Edit profile',
    'title callback' => 'entity_page_label',
    'title arguments' => array(3),
    'access callback' => 'profile2_access',
    'access arguments' => array(3, 'edit'),
    'page callback' => 'entity_get_form',
    'page arguments' => array(3),
    'type' => MENU_LOCAL_TASK,
  );
  $items['user/%user/edit/%profile2_menu/delete'] = array(
    // @see http://drupal.org/node/1863502
    'load arguments' => array(1, 'delete'),
    'load arguments' => array('%map', 'delete'),
    'title' => 'Delete profile',
    'access callback' => 'profile2_access',
    'access arguments' => array(3, 'delete'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('profile2_delete_confirm_form', 3),
    'type' => MENU_VISIBLE_IN_BREADCRUMB,
    'file' => 'profile2.pages.inc',
  );
  return $items;
}

/**
 * Menu argument callback; Loads a profile of a certain type for a given user.
 *
 * @param string $type_id
 *   The profile type ID to load.
 * @param Drupal\user\Plugin\Core\Entity\User $account
 *   The user account for which to load the profile.
 * @param string $op
 *   (optional) The operation to perform. If 'edit' and if there is no profile
 *   for the user account yet, a new profile entity will be created on the fly.
 *
 * @return Drupal\profile2\Plugin\Core\Entity\Profile|false
 *   The profile of type $type_id of the user account, or FALSE.
 */
// @see http://drupal.org/node/1863502
//function profile2_menu_load($type_id, User $account, $op = '') {
function profile2_menu_load($type_id, $map, $op = '') {
  if (is_array($map)) {
    if (!isset($map[1]) || !($map[1] instanceof User)) {
      return FALSE;
    }
    $account = $map[1];
  }
  else {
    $account = $map;
  }
  if ($type_id === '' || !$account->id()) {
    return FALSE;
  }
  $profiles = entity_load_multiple_by_properties('profile2', array(
    'uid' => $account->id(),
    'type' => $type_id,
  ));
  if ($op == 'edit' && !$profile = reset($profiles)) {
    $profile = entity_create('profile2', array(
      'type' => $type_id,
      'uid' => $account->id(),
    ));
  }
  return $profile;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function profile2_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($root_path === 'user/%/edit' || $root_path === 'user/%/edit/%') {
    $tabs = &$data['tabs'][1]['output'];
    // Determine the currently selected tab, if any.
    $selected_index = -1;
    $selected_id = '';
    foreach ($tabs as $index => &$tab) {
      if (isset($tab['#link']['path']) && $tab['#link']['path'] == 'user/%/edit/%') {
        $selected_index = $index;
        $selected_id = $router_item['original_map'][3];
      }
    }
    // Expand the dynamic %profile_menu argument into a tab for each type.
    $types = entity_load_multiple('profile2_type');
    foreach ($types as $type) {
      // If the current page is the active tab registered in hook_menu(), then
      // the menu router item with the dynamic argument will be exposed already.
      // We must not duplicate that tab, but in order to ensure that all of our
      // tabs appear in a consistent order when switching between tabs, we need
      // to re-inject it.
      if ($type->id() === $selected_id) {
        $tabs[$selected_index]['#link']['title'] = $type->label();
        $tabs[] = $tabs[$selected_index];
        unset($tabs[$selected_index]);
        continue;
      }
      $tabs[] = array(
        '#theme' => 'menu_local_task',
        '#link' => array(
          'title' => $type->label(),
          'href' => 'user/' . $router_item['original_map'][1] . '/edit/' . $type->id(),
          'localized_options' => array('html' => FALSE),
        ),
      );
    }
    if ($types) {
      $data['tabs'][1]['count']++;
    }
  }
}

/**
 * Menu argument loader; Load a profile type by string.
 *
 * @param string $id
 *   The machine-readable name of a profile type to load.
 *
 * @return Drupal\profile2\Plugin\Core\Entity\ProfileType|false
 *   A profile type array or FALSE if $type does not exist.
 */
function profile2_type_load($id) {
  return entity_load('profile2_type', $id);
}

/**
 * Implements hook_permission().
 */
function profile2_permission() {
  $permissions = array(
    'administer profile types' => array(
      'title' => t('Administer profile types'),
      'restrict access' => TRUE,
    ),
    'bypass profile access' => array(
      'title' => t('Bypass profile access'),
      'description' => t('View and edit all user profiles, including private field values.'),
      'restrict access' => TRUE,
    ),
  );
  // Generate per profile type permissions.
  foreach (entity_load_multiple('profile2_type') as $type) {
    $type_id = $type->id();
    $permissions += array(
      "view own $type_id profile" => array(
        'title' => t('%type: View own profile', array('%type' => $type->label())),
      ),
      "view any $type_id profile" => array(
        'title' => t('%type: View any profile', array('%type' => $type->label())),
      ),
      "edit own $type_id profile" => array(
        'title' => t('%type: Edit own profile', array('%type' => $type->label())),
      ),
      "edit any $type_id profile" => array(
        'title' => t('%type: Edit any profile', array('%type' => $type->label())),
      ),
      "delete own $type_id profile" => array(
        'title' => t('%type: Delete own profile', array('%type' => $type->label())),
      ),
      "delete any $type_id profile" => array(
        'title' => t('%type: Delete any profile', array('%type' => $type->label())),
      ),
    );
  }
  return $permissions;
}

/**
 * Implements hook_user_predelete().
 */
function profile2_user_predelete($account) {
  if ($profiles = entity_load_multiple_by_properties('profile2', array('uid' => $account->id()))) {
    entity_get_controller('profile2')->delete($profiles);
  }
}

/**
 * Implements hook_user_view().
 */
function profile2_user_view($account, $view_mode, $langcode) {
  foreach (entity_load_multiple('profile2_type') as $id => $type) {
    $profiles = entity_load_multiple_by_properties('profile2', array(
      'uid' => $account->id(),
      'type' => $id,
    ));

    if ($profile = reset($profiles)) {
      if ($profile->access('view')) {
        entity_render_controller('profile2')->buildContent(array($profile), 'account');
        $account->content['profile_' . $id] = array(
          '#theme' => 'profile2',
          '#title' => $profile->label(),
          '#prefix' => '<a id="profile-' . $profile->bundle() . '"></a>',
          '#profile' => $profile,
        ) + $profile->content;
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for the registration form.
 */
function profile2_form_user_register_form_alter(&$form, &$form_state) {
  foreach (entity_load_multiple('profile2_type') as $id => $type) {
    if ($type->get('registration')) {
      if (empty($form_state['profiles'][$id])) {
        $form_state['profiles'][$id] = entity_create('profile2', array(
          'type' => $id,
        ));
      }
      profile2_attach_form($form, $form_state);

      // Wrap each profile form in a fieldset.
      $form['profile'][$id] += array(
        '#type' => 'fieldset',
        '#title' => check_plain($type->label()),
      );
    }
  }
  if (!empty($form_state['profiles'])) {
    $form['#validate'][] = 'profile2_user_form_validate';
    $form['actions']['submit']['#submit'][] = 'profile2_user_form_submit';
  }
}

/**
 * Attaches the profile forms of the profiles set in $form_state['profiles'].
 *
 * Modules may alter the profile2 entity form regardless to which form it is
 * attached by making use of hook_form_profile2_form_alter().
 *
 * @param $form
 *   The form to which to attach the profile2 form. For each profile the form
 *   is added to @code $form['profile_' . $profile->type] @endcode. This helper
 *   also adds in a validation and a submit handler caring for the attached
 *   profile forms.
 *
 * @see profile2_user_form_validate()
 * @see profile2_user_form_submit()
 */
function profile2_attach_form(&$form, &$form_state) {
  foreach ($form_state['profiles'] as $bundle => $profile) {
    $form['profile'][$bundle]['#tree'] = TRUE;
    $form['profile'][$bundle]['#parents'] = array('profile', $bundle);

    field_attach_form('profile2', $profile, $form['profile'][$bundle], $form_state);

    if (count(field_info_instances('profile2', $bundle)) == 0) {
      $form['profile'][$bundle]['message'] = array(
        '#access' => user_access('administer profile types'),
        '#markup' => t('No fields have been associated with this profile type. Go to the <a href="!url">Profile types</a> page to add some fields.', array('!url' => url('admin/people/profiles'))),
      );
    }

    // Provide a central place for modules to alter the profile forms, but
    // skip that in case the caller cares about invoking the hooks.
    if (!isset($form_state['profile2_skip_hook'])) {
      $hooks = array();
      $hooks[] = 'form_' . $bundle . '_profile2_form';
      $hooks[] = 'form_profile2_form';
      drupal_alter($hooks, $form['profile'][$bundle], $form_state);
    }
  }
}

/**
 * Validation handler for the profile form.
 *
 * @see profile2_attach_form()
 */
function profile2_user_form_validate(&$form, &$form_state) {
  foreach ($form_state['profiles'] as $bundle => $profile) {
    if (isset($form_state['values']['profile'][$bundle])) {
      // @see entity_form_field_validate()
      $pseudo_entity = entity_create('profile2', array_merge($form_state['values']['profile'][$bundle], array(
        'type' => $bundle,
      )));
      field_attach_form_validate('profile2', $pseudo_entity, $form['profile'][$bundle], $form_state);
    }
  }
}

/**
 * Submit handler that builds and saves all profiles in the form.
 *
 * @see profile2_attach_form()
 */
function profile2_user_form_submit(&$form, &$form_state) {
  profile2_form_submit_build_profile($form, $form_state);

  foreach ($form_state['profiles'] as $bundle => $profile) {
    // During registration set the uid field of the newly created user.
    if (empty($profile->uid) && isset($form_state['user']->uid)) {
      $profile->uid = $form_state['user']->uid;
    }
    $profile->save();
  }
}

/**
 * Submit builder. Extracts the form values and updates the profile entities.
 *
 * @see profile2_attach_form()
 */
function profile2_form_submit_build_profile(&$form, &$form_state) {
  foreach ($form_state['profiles'] as $bundle => $profile) {
    // @see entity_form_submit_build_entity()
    if (isset($form['profile'][$bundle]['#entity_builders'])) {
      foreach ($form['profile'][$bundle]['#entity_builders'] as $function) {
        $function('profile2', $profile, $form['profile'][$bundle], $form_state);
      }
    }
    field_attach_submit('profile2', $profile, $form['profile'][$bundle], $form_state);
  }
}

/**
 * Helper function for checking profile access.
 */
function profile2_access(Profile $profile, $op, User $account = NULL) {
  if ($op == 'edit') {
    $op = ($profile->isNew() ? 'create' : 'update');
  }
  return $profile->access($op, $account);
}

/**
 * Implements hook_profile2_access().
 */
function profile2_profile2_access($op, Profile $profile, User $account) {
  if (user_access("$op any $profile->type profile", $account)) {
    return TRUE;
  }
  if (isset($profile->uid) && $profile->uid == $account->uid && user_access("$op own $profile->type profile", $account)) {
    return TRUE;
  }
  // Do not explicitly deny access so others may still grant access.
}

/**
 * Implements hook_theme().
 */
function profile2_theme() {
  return array(
    'profile2' => array(
      'render element' => 'elements',
      'template' => 'profile2',
    ),
  );
}

/**
 * Processes variables for profile2.tpl.php.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 *   - profile: The profile object.
 *   - view_mode: View mode; e.g., 'full', 'account'...
 *
 * @see profile2.tpl.php
 */
function template_preprocess_profile2(&$variables) {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  $variables['profile'] = $variables['elements']['#profile'];
  $profile = $variables['profile'];

  $variables['name'] = theme('username', array(
    'account' => $profile,
    'link_attributes' => array('rel' => 'author'),
  ));

  $uri = $profile->uri();
  $variables['url'] = url($uri['path'], $uri['options']);
  $variables['title'] = check_plain($profile->label());
  $variables['page'] = $variables['view_mode'] == 'full';
  $variables['type'] = $profile->bundle();

  // Helpful $content variable for templates.
  $variables += array('content' => array());
  foreach (element_children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }

  // Make the field variables available with the appropriate language.
  field_attach_preprocess('profile2', $profile, $variables['content'], $variables);

  // Add article ARIA role.
  $variables['attributes']['role'] = 'article';

  // Gather template classes.
  $variables['attributes']['class'][] = 'profile';
  $variables['attributes']['class'][] = drupal_html_class('profile-' . $profile->bundle());
  if ($variables['view_mode']) {
    $variables['attributes']['class'][] = drupal_html_class('view-mode-' . $variables['view_mode']);
  }
  if (isset($variables['preview'])) {
    $variables['attributes']['class'][] = 'preview';
  }

  $variables['theme_hook_suggestions'][] = 'profile2__' . $profile->bundle();
  $variables['theme_hook_suggestions'][] = 'profile2__' . $profile->uid;
}

/**
 * Implements hook_form_FORMID_alter().
 *
 * Adds a checkbox for controlling field view access to fields added to
 * profiles.
 */
function profile2_form_field_ui_field_settings_form_alter(&$form, &$form_state) {
  // Only add the field setting if this field is attached to a profile entity
  // bundle.
  if (isset($form['#field']['bundles']['profile2'])) {
    $form['field']['settings']['profile2_private'] = array(
      '#type' => 'checkbox',
      '#title' => t('Private field'),
      '#default_value' => !empty($form['#field']['settings']['profile2_private']),
      // Only expose the setting when editing the settings for a field attached
      // to a profile entity bundle. For other entity types, we just ensure that
      // the existing value is retained.
      '#access' => $form['#entity_type'] == 'profile2',
      '#description' => t('Only show the field content to the profile owner and administrators.'),
    );
  }
}

/**
 * Implements hook_field_access().
 */
function profile2_field_access($op, $field, $entity_type, $profile = NULL, $account = NULL) {
  if ($entity_type == 'profile2' && $op == 'view' && !empty($field['settings']['profile2_private']) && !user_access('bypass profile access', $account)) {
    // For profiles, deny general view access for private fields.
    if (!isset($profile)) {
      return FALSE;
    }
    // Also deny view access, if someone else views a private field.
    $account = isset($account) ? $account : $GLOBALS['user'];
    if ($account->uid != $profile->uid) {
      return FALSE;
    }
  }
}
